---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool
  namespace: cilium
spec:
  blocks:
    - cidr: 192.168.1.208/28  # 209 - 222
    - cidr: 192.168.1.224/28  # 225 - 238
  disabled: false
