---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: openbao-backend
  namespace: openbao
spec:
  provider:
    vault:
      server: 
      path: kv
      version: v2 # needs a data before secret name
      auth:
        tokenSecretRef:
          namespace: external-secrets
          name: openbao-token
          key: token
