---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao-backend
  namespace: openbao
spec:
  provider:
    vault:
      server: http://openbao-internal.openbao.svc.cluster.local:8200
      path: kv
      version: v2 # needs a data before secret name
      auth:
        tokenSecretRef: 
          namespace: external-secrets
          name: openbao-token
          key: token
