---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: extsecret-cloudflare-token
spec:
  externalSecretSpec:
    refreshInterval: 15s
    secretStoreRef:
      kind: ClusterSecretStore
      name: openbao-backend
    target:
      name: cloudflare-token
    dataFrom:
      - extract:
          key: cloudflare-token
          property: token
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - cert-manager
          - external-dns
