---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: extsecret-openbao-token
spec:
  externalSecretSpec:
    refreshInterval: 15s
    secretStoreRef:
      kind: ClusterSecretStore
      name: openbao-backend
    target:
      name: openbao-token
    data:
      - secretKey: token
        remoteRef:
          key: openbao-token
          property: token
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - external-secrets
