---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - addresspool.yml
  - ciliuml2policy.yml
  - cluster-issuer.yml
  - cluster-secretstore.yml
  - extsecret-cloudflare-token.yml
  - extsecret-openbao-token.yml
  - grafana-gateway.yml
  - longhorn-gateway.yml
  - openbao-gateway.yml
  - prometheus-gateway.yml
