apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - addresspool.yml
  - ciliuml2policy.yml
  - cloudflare-token.yml
  - cluster-issuer.yml
  - cluster-secretstore.yml
  - grafana-gateway.yml
  - hubble-gateway.yml
  - longhorn-gateway.yml
  - openbao-gateway.yml
  - prometheus-gateway.yml
